sudo: required

compiler:
    - gcc

os:
    - linux

dist: trusty

language: c

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - check
            - lcov
            - clang-3.8
            - clang-format-3.8
            - llvm-3.8

before_install:
    - gem install coveralls-lcov
    - wget -nc https://github.com/clearlinux/bsdiff/releases/download/v1.0.1/bsdiff-1.0.1.tar.xz
    - xz -d bsdiff-1.0.1.tar.xz
    - tar xf bsdiff-1.0.1.tar
    - cd bsdiff-1.0.1 && autoreconf -fis && ./configure && make && sudo make install
    - cd ..
    - wget -nc https://curl.haxx.se/download/curl-7.48.0.tar.gz
    - tar xzf curl-7.48.0.tar.gz
    - cd curl-7.48.0 && ./configure && make && sudo make install
    - cd ..
    - wget -nc --no-check-certificate http://downloads.sourceforge.net/ltp/lcov-1.10.tar.gz
    - tar xzf lcov-1.10.tar.gz
    - cd lcov-1.10 && make && sudo make install
    - cd ..

script:
    - lcov --version | grep "1.10"
    - mkdir m4 && autoreconf -fis && ./configure --enable-coverage && make && make check
    - clang-format-3.8 -i $(find . -name '*.[ch]') && git diff --exit-code


after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - lcov --compat-libtool --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
    - coveralls-lcov coverage.info
